title: bringa.io Docs
description: Forkable sharing and borrowing app documentation.
url: https://bringaio.github.io
baseurl: /app.bringa.io
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - prompts/
defaults:
  - scope:
      path: ""
    values:
      layout: default
